[package]
name = "spacetimemc-server"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
spacetimedb = "1.1"
log.workspace = true
uuid = { version = "1.17", features = [] }
